name: deploy

on:
  push:
    branch: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build pug
        run: deno run --allow-read --allow-write --unstable build.ts --production

      - name: clear gitignore
        run: |
          rm -rf .git .github .gitignore
          find static -type f -not -name '*.ls' -print0 | xargs -0 rm --

      - name: Upload to deploy branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: codehz/ipfs-paste-deploy
          target_branch: deploy
          build_dir: .
          commit_message: Deploy for deno deploy
        env:
          GH_PAT: ${{ secrets.MY_PAT }}